/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список предстоящих встреч (владелец). */
        get: operations["Bookings_list"];
        put?: never;
        /** @description Создать бронирование (гость). 409 если время занято, 422 если невалидно. */
        post: operations["Bookings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Детали бронирования. */
        get: operations["Bookings_read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список типов событий (владелец и гость). */
        get: operations["EventTypes_list"];
        put?: never;
        /** @description Создать тип события (владелец). */
        post: operations["EventTypes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Один тип события. */
        get: operations["EventTypes_read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Доступные свободные слоты.
         *
         *     Окно ограничено ближайшими 14 днями от текущего момента.
         *     Если `from`/`to` не заданы — используется [сейчас; сейчас + 14 дней].
         *     Запрос за пределами 14-дневного окна обрезается до него.
         */
        get: operations["EventTypes_slots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Профиль единственного владельца календаря (имя, таймзона). */
        get: operations["OwnerEndpoint_read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Бронирование, созданное гостем. */
        Booking: {
            id: string;
            eventTypeId: string;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            guestName: string;
            guestEmail: string;
            notes?: string;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Данные для создания бронирования. */
        BookingCreate: {
            eventTypeId: string;
            /**
             * Format: date-time
             * @description Время старта (UTC). Правила валидации (иначе 422):
             *     - выровнено по 30-минутной сетке (минуты 00 или 30, секунды 0);
             *     - не в прошлом;
             *     - в пределах рабочих часов владельца 09:00–18:00 его таймзоны;
             *     - в пределах ближайших 14 дней от текущего момента.
             */
            start: string;
            guestName: string;
            guestEmail: string;
            notes?: string;
        };
        /** @description Время уже занято другим бронированием. */
        ConflictError: {
            /** @enum {string} */
            code: "TIME_SLOT_TAKEN";
            message: string;
        };
        /** @description Тип события/звонка, который создаёт владелец. */
        EventType: {
            id: string;
            title: string;
            description?: string;
            /**
             * Format: int32
             * @description Длительность в минутах. На текущем этапе всегда 30.
             * @default 30
             */
            durationMinutes: number;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Данные для создания типа события. */
        EventTypeCreate: {
            title: string;
            description?: string;
        };
        /** @description Запрошенный ресурс не найден. */
        NotFoundError: {
            /** @enum {string} */
            code: "NOT_FOUND";
            message: string;
        };
        /** @description Владелец календаря (единственный, предопределён). */
        Owner: {
            id: string;
            name: string;
            /** @description IANA timezone, например "Europe/Moscow". */
            timezone: string;
        };
        /** @description Вычисляемый 30-минутный интервал доступности (не хранится). */
        Slot: {
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            available: boolean;
        };
        /** @description Невалидные данные: время вне окна, не выровнено по сетке, в прошлом и т.п. */
        ValidationError: {
            /** @enum {string} */
            code: "VALIDATION_FAILED";
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Bookings_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
        };
    };
    Bookings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Время уже занято другим бронированием. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
            /** @description Невалидные данные: время вне окна, не выровнено по сетке, в прошлом и т.п. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    Bookings_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Запрошенный ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    EventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    EventTypes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Невалидные данные: время вне окна, не выровнено по сетке, в прошлом и т.п. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    EventTypes_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Запрошенный ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    EventTypes_slots: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            /** @description Запрошенный ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    OwnerEndpoint_read: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Owner"];
                };
            };
        };
    };
}
